[versions]
kotlin = "2.2.0"
langchain4j = "1.7.1"
langchain4j-integrations = "1.7.1-beta14"
spring-boot = "3.5.4"
spring-dependency-management = "1.1.7"

[libraries]
langchain4j = { module = "dev.langchain4j:langchain4j", version.ref = "langchain4j" }
langchain4j-open-ai-spring-boot-starter = { module = "dev.langchain4j:langchain4j-open-ai-spring-boot-starter", version.ref = "langchain4j-integrations" }
langchain4j-embeddings-all-minilm-l6-v2 = { module = "dev.langchain4j:langchain4j-embeddings-all-minilm-l6-v2", version.ref = "langchain4j-integrations" }
langchain4j-weaviate = { module = "dev.langchain4j:langchain4j-weaviate", version.ref = "langchain4j-integrations" }

[plugins]
spring-dependencymanagement = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id  = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id  ="org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
